name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

    - name: Send .env to VM
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        scp -o StrictHostKeyChecking=no .env ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }}:/app/NutritionManager

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          cd /app/NutritionManager
          git pull origin main
          docker compose up --build
        EOF
