name: Deploy para GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer deploy
      run: |
        ssh ${{ secrets.GCP_SSH_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          git clone git@github.com:moraisz/NutritionManager.git /app/
          cd /app/
          git pull origin main
          docker-compose up -d --build
        EOF
